In [1]:
import numpy as np
import xtensor_climate_fun as xt

from IPython.display import display

### Function example1

In [2]:
print(xt.snyder_edd.__doc__)

snyder_edd(arg0: numpy.ndarray[float], arg1: numpy.ndarray[float], arg2: float) -> numpy.ndarray[float]

Return the snyder EDD



In [3]:
a = np.arange(15).reshape(3, 5) + 5
b = a + 10
edd = xt.snyder_edd(a, b, 10)
display(a)
display(b)
display(edd)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[  1.59154943,   2.12348782,   2.72065891,   3.38773784,   4.1355986 ],
       [  5.        ,   6.        ,   7.        ,   8.        ,   9.        ],
       [ 10.        ,  11.        ,  12.        ,  13.        ,  14.        ]])

In [4]:
def py_snyder_edd(tasmin, tasmax, threshold):

    # compute useful quantities for use in the transformation
    snyder_mean = ((tasmax + tasmin)/2)
    snyder_width = ((tasmax - tasmin)/2)
    snyder_theta = np.arcsin( (threshold - snyder_mean)/snyder_width )

    # the trasnformation is computed using numpy arrays, taking advantage of
    # numpy's second where clause. Note that in the current dev build of
    # xarray, xr.where allows this functionality. As soon as this goes live,
    # this block can be replaced with xarray
    res = np.where(
        tasmin < threshold,
        np.where(
            tasmax > threshold,
            ((snyder_mean - threshold) * (np.pi/2 - snyder_theta)
                + (snyder_width * np.cos(snyder_theta))) / np.pi,
            0),
        snyder_mean - threshold)

    return res

In [5]:
tasmin = np.random.random((1000, 5000, 10))*15
tasmax = tasmin + 5

In [6]:
% timeit py_snyder_edd(tasmin, tasmax, 10)

//anaconda/envs/xtensor/lib/python3.5/site-packages/ipykernel/__main__.py:6: RuntimeWarning: invalid value encountered in arcsin


6.46 s ± 455 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
% timeit xt.snyder_edd(tasmin, tasmax, 10)

5.06 s ± 176 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Function example2

In [8]:
print(xt.example2.__doc__)

example2(arg0: numpy.ndarray[float]) -> numpy.ndarray[float]

Return the the specified array plus 2



In [9]:
a = np.arange(15).reshape(3, 5)
b = xt.example2(a)
display(a)
display(b)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[  2.,   3.,   4.,   5.,   6.],
       [  7.,   8.,   9.,  10.,  11.],
       [ 12.,  13.,  14.,  15.,  16.]])

### Function readme_example1

In [10]:
print(xt.readme_example1.__doc__)

readme_example1(arg0: numpy.ndarray[float]) -> float

Accumulate the sines of all the values of the specified array



In [11]:
PI = np.pi
a = np.linspace(0, PI, 100)
b = xt.readme_example1(a)
display(a)
display(np.sin(a).sum())
display(b)

array([ 0.        ,  0.03173326,  0.06346652,  0.09519978,  0.12693304,
        0.1586663 ,  0.19039955,  0.22213281,  0.25386607,  0.28559933,
        0.31733259,  0.34906585,  0.38079911,  0.41253237,  0.44426563,
        0.47599889,  0.50773215,  0.53946541,  0.57119866,  0.60293192,
        0.63466518,  0.66639844,  0.6981317 ,  0.72986496,  0.76159822,
        0.79333148,  0.82506474,  0.856798  ,  0.88853126,  0.92026451,
        0.95199777,  0.98373103,  1.01546429,  1.04719755,  1.07893081,
        1.11066407,  1.14239733,  1.17413059,  1.20586385,  1.23759711,
        1.26933037,  1.30106362,  1.33279688,  1.36453014,  1.3962634 ,
        1.42799666,  1.45972992,  1.49146318,  1.52319644,  1.5549297 ,
        1.58666296,  1.61839622,  1.65012947,  1.68186273,  1.71359599,
        1.74532925,  1.77706251,  1.80879577,  1.84052903,  1.87226229,
        1.90399555,  1.93572881,  1.96746207,  1.99919533,  2.03092858,
        2.06266184,  2.0943951 ,  2.12612836,  2.15786162,  2.18

63.02006849910228

63.02006849910227

### Function vectorize_example1

In [12]:
print(xt.vectorize_example1.__doc__)

vectorize_example1(arg0: numpy.ndarray[float], arg1: numpy.ndarray[float]) -> numpy.ndarray[float]

Add the sine and and cosine of the two specified values



In [13]:
PI = np.pi
a = np.linspace(0, PI, 10)
b = np.linspace(0, 2*PI, 10)
c = xt.vectorize_example1(a, b)
d = np.sin(a)+np.cos(b)
display(a)
display(b)
display(c)
display(np.isclose(c, d))

array([ 0.        ,  0.34906585,  0.6981317 ,  1.04719755,  1.3962634 ,
        1.74532925,  2.0943951 ,  2.44346095,  2.7925268 ,  3.14159265])

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

array([ 1.        ,  1.10806459,  0.81643579,  0.3660254 ,  0.04511513,
        0.04511513,  0.3660254 ,  0.81643579,  1.10806459,  1.        ])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)